export const marketingAssets = {
  headerLogo: '/assets/marketing/header-logo.png',
  footerLogo: '/assets/marketing/footer-logo.png',
  footerLogoAlt: '/assets/marketing/footer-logo-alt.png',
  socialInstagram: '/assets/marketing/social-instagram.svg',
  socialTwitter: '/assets/marketing/social-twitter.svg',
  socialFacebook: '/assets/marketing/social-facebook.svg',
  socialYoutube: '/assets/marketing/social-youtube.svg',
  paymentMastercard: '/assets/marketing/payment-mastercard.png',
  paymentVisa: '/assets/marketing/payment-visa.png',
  paymentPaypal: '/assets/marketing/payment-paypal.png',
  footerLine: '/assets/marketing/footer-line.svg',
  homeHero: '/assets/marketing/home-hero.jpg',
  homeCatalog: '/assets/marketing/home-catalog.jpg',
  homeMockup: '/assets/marketing/home-mockup.jpg',
  homeOrders: '/assets/marketing/home-orders.jpg',
  homeFundraiser: '/assets/marketing/home-fundraiser.jpg',
  aboutHero: '/assets/marketing/about-hero.png',
  aboutTrust: '/assets/marketing/about-trust.png',
  aboutSavings: '/assets/marketing/about-savings.jpg',
  aboutOccasions: '/assets/marketing/about-occasions.png',
  fundraiserHero: '/assets/marketing/fundraiser-hero.jpg',
  fundraiserContent: '/assets/marketing/fundraiser-content.jpg',
  fundraiserDetailFallback: '/assets/marketing/fundraiser-detail-fallback.jpg',
} as const;
